= Professionelle Softwareentwicklung: Praktische Übung 8
:icons: font
:icon-set: fa
:experimental:
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:stem: latexmath
endif::[]

== Vorbereitung 

Die Vorbereitungsarbeiten müssen Sie *vor der praktischen Übung* abschließen. 

Wir erwarten von Ihnen, dass Sie ...

* ein Headset o.ä. bereithalten. Testen Sie Ihr Audiosetup mit anderen Kommilitonen (z.B. Ihrer Gruppe) aus. Sie können dazu zum Beispiel https://test.bigbluebutton.org/ benutzen. 
* eine IDE installiert haben und mit der Entwicklungsumgebung flüssig umgehen können.
* sich mit Code Smells beschäftigt haben und den Aufgabentext unten gelesen haben
* sich das https://youtu.be/oJCccI2Fwf0[Video] zum Testing des Programms angesehen haben 

== Ziele der Übung

Das Lernziel der Aufgabe ist es, testgetriebene Entwicklung praktisch einzuüben.  

== Ablauf der Übung

. Schalten Sie *mindestens* das Mikrofon, aber besser auch die Kamera, ein 
. Am Anfang gibt es eine kurze Vorstellungsrunde 
. In der Gruppe wird kurz diskutiert, wie die Lösung angegangen werden soll und es werden noch offene Fragen geklärt
. Es wird festgelegt, in welcher Reihenfolge die "Driver" Rolle übernommen wird
. Die erste Person teilt Ihren Screen und übernimmt mithilfe von `mob` die Session
. Es wird an der Problemstellung gemeinsam gearbeitet nach den Regeln des Mob Programmings 
. Nach ca. der Hälfte der Zeit gibt es ein Feedback durch die Tutorin oder den Tutor
. Es wird weiter an der Problemstellung gearbeitet
. ca. 10 Minuten vor Ende der Session bekommen Sie Ihre Abschlussbewertung 

== Aufgabe: Ugly Trivia Game

Wir wollen diese Woche ein Programm verbessern. Leider wurde das Programm nicht testgetrieben entwickelt oder zumindest getestet. Es gibt keine Unit-Tests und das Schreiben der Tests ist auch nicht ohne ein Refactoring machbar. Wir werden daher zunächst ein provisorisches Sicherheitsnetz benötigen.  

Dabei verwenden wir eine Technik, die manchmal als "Golden Master Technik" bezeichnet wird. Schauen Sie sich das folgende https://youtu.be/oJCccI2Fwf0[Video] an, in dem diese Form des Testings gezeigt wird. 

IMPORTANT: Es handelt sich um ein Provisorium, damit wir den Code so umschreiben können, dass er testbarer ist. Das Ziel ist es, das Provisorium loszuwerden. 

Ihre Aufgabe ist die Verbesserung des Programms durch Beseitigung der Code Smells. Verwenden Sie auch die anderen Prinzipien, die Sie kennengelernt haben, um die Qualität des Programms zu verbessern. Arbeiten Sie auf eine bessere Testbarkeit des Programms hin und fügen Sie schrittweise "echte" Unit-Tests hinzu. 

* Tipp für den Start: Bringen Sie die Ausgabe unter Ihre Kontrolle durch Einführung einer Klasse, die `System.out` wrappt.
* Wenn Sie Tests schreiben, dann sind das keine Tests im Sinne von TDD. Die Tests müssen von Anfang an grün sein.

IMPORTANT: Zementieren Sie nicht die bestehenden Methoden mit Unit Tests fest, das behindert Sie beim Refactoring.  *Schreiben Sie keine Unit Tests für die bestehenden Methoden*, sondern versuchen Sie eine Idee zu entwickeln, wie die Klasse optimalerweise verwendet werden sollte und schreiben Sie Tests für diese optimale API. Wenn Sie noch nicht wissen, wie die API aussehen könnte, verbessern Sie erst den bestehenden Code. 
 
Im Optimalfall kommen Sie am Ende zu einem Zustand, in dem Sie die provisorischen Tests löschen können.

== Verhaltensregeln

Wir erwarten von Ihnen einen respektvollen Umgang miteinander. Es gilt grundsätzlich bei uns der https://berlincodeofconduct.org/de/[Berlin Code of Conduct]. Die TutorInnen haben die Aufgabe, die Einhaltung der Regeln zu überwachen und können bei Verstößen gegen den Verhaltenskodex Personen aus der praktischen Übung entfernen.   
